export default [
  { sub: 'AC', title: 'Acre' },
  { sub: 'AL', title: 'Alagoas' },
  { sub: 'AP', title: 'Amapá' },
  { sub: 'AM', title: 'Amazonas' },
  { sub: 'BA', title: 'Bahia' },
  { sub: 'CE', title: 'Ceará' },
  { sub: 'DF', title: 'Distrito Federal' },
  { sub: 'ES', title: 'Espirito Santo' },
  { sub: 'GO', title: 'Goiás' },
  { sub: 'MA', title: 'Maranhão' },
  { sub: 'MS', title: 'Mato Grosso do Sul' },
  { sub: 'MT', title: 'Mato Grosso' },
  { sub: 'MG', title: 'Minas Gerais' },
  { sub: 'PA', title: 'Pará' },
  { sub: 'PB', title: 'Paraíba' },
  { sub: 'PR', title: 'Paraná' },
  { sub: 'PE', title: 'Pernambuco' },
  { sub: 'PI', title: 'Piauí' },
  { sub: 'RJ', title: 'Rio de Janeiro' },
  { sub: 'RN', title: 'Rio Grande do Norte' },
  { sub: 'RS', title: 'Rio Grande do Sul' },
  { sub: 'RO', title: 'Rondônia' },
  { sub: 'RR', title: 'Roraima' },
  { sub: 'SC', title: 'Santa Catarina' },
  { sub: 'SP', title: 'São Paulo' },
  { sub: 'SE', title: 'Sergipe' },
  { sub: 'TO', title: 'Tocantins' }
]
